import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

const ppEditorial = localFont({
    src: [
      {
        path: './fonts/PPEditorialNew-Regular.otf',
        weight: '400',
        style: 'normal',
      }
    ], variable: "--font-pp-editorial"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSans.variable} ${ppEditorial.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
